// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: main/proto/datamodel.proto

package serialization.protobuf;

public final class Datamodel {
  private Datamodel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface OnlineStoreUserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:serialization.protobuf.OnlineStoreUser)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int32 storeId = 1;</code>
     */
    boolean hasStoreId();
    /**
     * <code>required int32 storeId = 1;</code>
     */
    int getStoreId();

    /**
     * <code>required string userName = 2;</code>
     */
    boolean hasUserName();
    /**
     * <code>required string userName = 2;</code>
     */
    java.lang.String getUserName();
    /**
     * <code>required string userName = 2;</code>
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>optional string userEmail = 4;</code>
     */
    boolean hasUserEmail();
    /**
     * <code>optional string userEmail = 4;</code>
     */
    java.lang.String getUserEmail();
    /**
     * <code>optional string userEmail = 4;</code>
     */
    com.google.protobuf.ByteString
        getUserEmailBytes();
  }
  /**
   * Protobuf type {@code serialization.protobuf.OnlineStoreUser}
   */
  public  static final class OnlineStoreUser extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:serialization.protobuf.OnlineStoreUser)
      OnlineStoreUserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use OnlineStoreUser.newBuilder() to construct.
    private OnlineStoreUser(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private OnlineStoreUser() {
      userName_ = "";
      userEmail_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private OnlineStoreUser(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              storeId_ = input.readInt32();
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              userName_ = bs;
              break;
            }
            case 34: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000004;
              userEmail_ = bs;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return serialization.protobuf.Datamodel.internal_static_serialization_protobuf_OnlineStoreUser_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return serialization.protobuf.Datamodel.internal_static_serialization_protobuf_OnlineStoreUser_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              serialization.protobuf.Datamodel.OnlineStoreUser.class, serialization.protobuf.Datamodel.OnlineStoreUser.Builder.class);
    }

    private int bitField0_;
    public static final int STOREID_FIELD_NUMBER = 1;
    private int storeId_;
    /**
     * <code>required int32 storeId = 1;</code>
     */
    public boolean hasStoreId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>required int32 storeId = 1;</code>
     */
    public int getStoreId() {
      return storeId_;
    }

    public static final int USERNAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object userName_;
    /**
     * <code>required string userName = 2;</code>
     */
    public boolean hasUserName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>required string userName = 2;</code>
     */
    public java.lang.String getUserName() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string userName = 2;</code>
     */
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      java.lang.Object ref = userName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USEREMAIL_FIELD_NUMBER = 4;
    private volatile java.lang.Object userEmail_;
    /**
     * <code>optional string userEmail = 4;</code>
     */
    public boolean hasUserEmail() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>optional string userEmail = 4;</code>
     */
    public java.lang.String getUserEmail() {
      java.lang.Object ref = userEmail_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          userEmail_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string userEmail = 4;</code>
     */
    public com.google.protobuf.ByteString
        getUserEmailBytes() {
      java.lang.Object ref = userEmail_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        userEmail_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasStoreId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasUserName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeInt32(1, storeId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, userName_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, userEmail_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, storeId_);
      }
      if (((bitField0_ & 0x00000002) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, userName_);
      }
      if (((bitField0_ & 0x00000004) != 0)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, userEmail_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof serialization.protobuf.Datamodel.OnlineStoreUser)) {
        return super.equals(obj);
      }
      serialization.protobuf.Datamodel.OnlineStoreUser other = (serialization.protobuf.Datamodel.OnlineStoreUser) obj;

      if (hasStoreId() != other.hasStoreId()) return false;
      if (hasStoreId()) {
        if (getStoreId()
            != other.getStoreId()) return false;
      }
      if (hasUserName() != other.hasUserName()) return false;
      if (hasUserName()) {
        if (!getUserName()
            .equals(other.getUserName())) return false;
      }
      if (hasUserEmail() != other.hasUserEmail()) return false;
      if (hasUserEmail()) {
        if (!getUserEmail()
            .equals(other.getUserEmail())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStoreId()) {
        hash = (37 * hash) + STOREID_FIELD_NUMBER;
        hash = (53 * hash) + getStoreId();
      }
      if (hasUserName()) {
        hash = (37 * hash) + USERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getUserName().hashCode();
      }
      if (hasUserEmail()) {
        hash = (37 * hash) + USEREMAIL_FIELD_NUMBER;
        hash = (53 * hash) + getUserEmail().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static serialization.protobuf.Datamodel.OnlineStoreUser parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static serialization.protobuf.Datamodel.OnlineStoreUser parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static serialization.protobuf.Datamodel.OnlineStoreUser parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static serialization.protobuf.Datamodel.OnlineStoreUser parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static serialization.protobuf.Datamodel.OnlineStoreUser parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static serialization.protobuf.Datamodel.OnlineStoreUser parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static serialization.protobuf.Datamodel.OnlineStoreUser parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static serialization.protobuf.Datamodel.OnlineStoreUser parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static serialization.protobuf.Datamodel.OnlineStoreUser parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static serialization.protobuf.Datamodel.OnlineStoreUser parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static serialization.protobuf.Datamodel.OnlineStoreUser parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static serialization.protobuf.Datamodel.OnlineStoreUser parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(serialization.protobuf.Datamodel.OnlineStoreUser prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code serialization.protobuf.OnlineStoreUser}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:serialization.protobuf.OnlineStoreUser)
        serialization.protobuf.Datamodel.OnlineStoreUserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return serialization.protobuf.Datamodel.internal_static_serialization_protobuf_OnlineStoreUser_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return serialization.protobuf.Datamodel.internal_static_serialization_protobuf_OnlineStoreUser_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                serialization.protobuf.Datamodel.OnlineStoreUser.class, serialization.protobuf.Datamodel.OnlineStoreUser.Builder.class);
      }

      // Construct using serialization.protobuf.Datamodel.OnlineStoreUser.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        storeId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        userName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        userEmail_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return serialization.protobuf.Datamodel.internal_static_serialization_protobuf_OnlineStoreUser_descriptor;
      }

      @java.lang.Override
      public serialization.protobuf.Datamodel.OnlineStoreUser getDefaultInstanceForType() {
        return serialization.protobuf.Datamodel.OnlineStoreUser.getDefaultInstance();
      }

      @java.lang.Override
      public serialization.protobuf.Datamodel.OnlineStoreUser build() {
        serialization.protobuf.Datamodel.OnlineStoreUser result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public serialization.protobuf.Datamodel.OnlineStoreUser buildPartial() {
        serialization.protobuf.Datamodel.OnlineStoreUser result = new serialization.protobuf.Datamodel.OnlineStoreUser(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.storeId_ = storeId_;
          to_bitField0_ |= 0x00000001;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          to_bitField0_ |= 0x00000002;
        }
        result.userName_ = userName_;
        if (((from_bitField0_ & 0x00000004) != 0)) {
          to_bitField0_ |= 0x00000004;
        }
        result.userEmail_ = userEmail_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof serialization.protobuf.Datamodel.OnlineStoreUser) {
          return mergeFrom((serialization.protobuf.Datamodel.OnlineStoreUser)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(serialization.protobuf.Datamodel.OnlineStoreUser other) {
        if (other == serialization.protobuf.Datamodel.OnlineStoreUser.getDefaultInstance()) return this;
        if (other.hasStoreId()) {
          setStoreId(other.getStoreId());
        }
        if (other.hasUserName()) {
          bitField0_ |= 0x00000002;
          userName_ = other.userName_;
          onChanged();
        }
        if (other.hasUserEmail()) {
          bitField0_ |= 0x00000004;
          userEmail_ = other.userEmail_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasStoreId()) {
          return false;
        }
        if (!hasUserName()) {
          return false;
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        serialization.protobuf.Datamodel.OnlineStoreUser parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (serialization.protobuf.Datamodel.OnlineStoreUser) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int storeId_ ;
      /**
       * <code>required int32 storeId = 1;</code>
       */
      public boolean hasStoreId() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>required int32 storeId = 1;</code>
       */
      public int getStoreId() {
        return storeId_;
      }
      /**
       * <code>required int32 storeId = 1;</code>
       */
      public Builder setStoreId(int value) {
        bitField0_ |= 0x00000001;
        storeId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int32 storeId = 1;</code>
       */
      public Builder clearStoreId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        storeId_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object userName_ = "";
      /**
       * <code>required string userName = 2;</code>
       */
      public boolean hasUserName() {
        return ((bitField0_ & 0x00000002) != 0);
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public Builder setUserName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public Builder clearUserName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        userName_ = getDefaultInstance().getUserName();
        onChanged();
        return this;
      }
      /**
       * <code>required string userName = 2;</code>
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        userName_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object userEmail_ = "";
      /**
       * <code>optional string userEmail = 4;</code>
       */
      public boolean hasUserEmail() {
        return ((bitField0_ & 0x00000004) != 0);
      }
      /**
       * <code>optional string userEmail = 4;</code>
       */
      public java.lang.String getUserEmail() {
        java.lang.Object ref = userEmail_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            userEmail_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string userEmail = 4;</code>
       */
      public com.google.protobuf.ByteString
          getUserEmailBytes() {
        java.lang.Object ref = userEmail_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          userEmail_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string userEmail = 4;</code>
       */
      public Builder setUserEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        userEmail_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string userEmail = 4;</code>
       */
      public Builder clearUserEmail() {
        bitField0_ = (bitField0_ & ~0x00000004);
        userEmail_ = getDefaultInstance().getUserEmail();
        onChanged();
        return this;
      }
      /**
       * <code>optional string userEmail = 4;</code>
       */
      public Builder setUserEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        userEmail_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:serialization.protobuf.OnlineStoreUser)
    }

    // @@protoc_insertion_point(class_scope:serialization.protobuf.OnlineStoreUser)
    private static final serialization.protobuf.Datamodel.OnlineStoreUser DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new serialization.protobuf.Datamodel.OnlineStoreUser();
    }

    public static serialization.protobuf.Datamodel.OnlineStoreUser getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<OnlineStoreUser>
        PARSER = new com.google.protobuf.AbstractParser<OnlineStoreUser>() {
      @java.lang.Override
      public OnlineStoreUser parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new OnlineStoreUser(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<OnlineStoreUser> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OnlineStoreUser> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public serialization.protobuf.Datamodel.OnlineStoreUser getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_serialization_protobuf_OnlineStoreUser_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_serialization_protobuf_OnlineStoreUser_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\032main/proto/datamodel.proto\022\026serializat" +
      "ion.protobuf\"G\n\017OnlineStoreUser\022\017\n\007store" +
      "Id\030\001 \002(\005\022\020\n\010userName\030\002 \002(\t\022\021\n\tuserEmail\030" +
      "\004 \001(\tB\030\n\026serialization.protobuf"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_serialization_protobuf_OnlineStoreUser_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_serialization_protobuf_OnlineStoreUser_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_serialization_protobuf_OnlineStoreUser_descriptor,
        new java.lang.String[] { "StoreId", "UserName", "UserEmail", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
